In [4]:
import pandas as pd

# data frame

### literally the only difference between read table and read CSV is that read CSV uses the comma as the default separator

### Here the data is already in csv file so no need to use sep as comma,suppose if we use read_table we have to use sep.

In [8]:
#pd.read_table("http://bit.ly/uforeports,sep=",")
ufo=pd.read_csv("http://bit.ly/uforeports")

In [7]:
ufo

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
5,Valley City,NaN,DISK,ND,9/15/1934 15:30
6,Crater Lake,NaN,CIRCLE,CA,6/15/1935 0:00
7,Alma,NaN,DISK,MI,7/15/1936 0:00
8,Eklutna,NaN,CIGAR,AK,10/15/1936 17:00
9,Hubbard,NaN,CYLINDER,OR,6/15/1937 0:00
10,Fontana,NaN,LIGHT,CA,8/15/1937 21:00
11,Waterloo,NaN,FIREBALL,AL,6/1/1939 20:00
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
13,Keokuk,NaN,OVAL,IA,7/7/1939 2:00
14,Ludington,NaN,DISK,MI,6/1/1941 13:00
15,Forest Home,NaN,CIRCLE,CA,7/2/1941 11:30
16,Los Angeles,NaN,NaN,CA,2/25/1942 0:00
17,Hapeville,NaN,NaN,GA,6/1/1942 22:30
18,Oneida,NaN,RECTANGLE,TN,7/15/1942 1:00
19,Bering Sea,RED,OTHER,AK,4/30/1943 23:00
20,Nebraska,NaN,DISK,NE,6/1/1943 15:00
21,NaN,NaN,NaN,LA,8/15/1943 0:00
22,NaN,NaN,LIGHT,LA,8/15/1943 0:00
23,Owensboro,NaN,RECTANGLE,KY,10/15/1943 11:00
24,Wilderness,NaN,DISK,WV,1/1/1944 10:00
25,San Diego,NaN,CIGAR,CA,1/1/1944 12:00
26,Wilderness,NaN,DISK,WV,1/1/1944 12:00
27,Clovis,NaN,DISK,NM,4/2/1944 11:00
28,Los Alamos,NaN,DISK,NM,6/1/1944 12:00
29,Ft. Duschene,NaN,DISK,UT,6/30/1944 10:00
...,...,...,...,...,...
18211,Holyoke,NaN,DIAMOND,MA,12/28/2000 18:00
18212,Carson,NaN,DISK,CA,12/28/2000 18:20
18213,Pasadena,GREEN,FIREBALL,CA,12/28/2000 19:10
18214,Austin,NaN,FORMATION,TX,12/29/2000 0:00
18215,El Campo,NaN,OTHER,TX,12/29/2000 9:00
18216,Garden Grove,ORANGE,LIGHT,CA,12/29/2000 16:10
18217,Berthoud Pass,NaN,TRIANGLE,CO,12/29/2000 19:30
18218,Sisterdale,NaN,DIAMOND,TX,12/29/2000 20:00
18219,Garden Grove,NaN,CHEVRON,CA,12/29/2000 20:30
18220,Shasta Lake,BLUE,DISK,CA,12/29/2000 20:30
18221,Franklin,NaN,DISK,NH,12/29/2000 20:50
18222,Albrightsville,NaN,OTHER,PA,12/29/2000 21:00
18223,Greenville,NaN,NaN,SC,12/29/2000 22:00
18224,Eufaula,NaN,DISK,OK,12/29/2000 23:30
18225,Simi Valley,NaN,FORMATION,CA,12/30/2000 10:00
18226,San Francisco,NaN,FORMATION,CA,12/30/2000 22:00
18227,San Francisco,NaN,TRIANGLE,CA,12/30/2000 22:00
18228,Kingsville,NaN,LIGHT,TX,12/31/2000 4:00
18229,Chicago,NaN,DISK,IL,12/31/2000 11:45
18230,Pismo Beach,NaN,OVAL,CA,12/31/2000 20:00
18231,Pismo Beach,NaN,OVAL,CA,12/31/2000 20:00
18232,Lodi,NaN,NaN,WI,12/31/2000 20:30
18233,Anchorage,RED,VARIOUS,AK,12/31/2000 21:00
18234,Capitola,NaN,TRIANGLE,CA,12/31/2000 22:00
18235,Fountain Hills,NaN,NaN,AZ,12/31/2000 23:00
18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00
18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00
18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45
18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45
18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59

In [5]:
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [9]:
type(ufo)

pandas.core.frame.DataFrame

### It displays the city column

In [11]:
ufo["City"]

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
5                 Valley City
6                 Crater Lake
7                        Alma
8                     Eklutna
9                     Hubbard
10                    Fontana
11                   Waterloo
12                     Belton
13                     Keokuk
14                  Ludington
15                Forest Home
16                Los Angeles
17                  Hapeville
18                     Oneida
19                 Bering Sea
20                   Nebraska
21                        NaN
22                        NaN
23                  Owensboro
24                 Wilderness
25                  San Diego
26                 Wilderness
27                     Clovis
28                 Los Alamos
29               Ft. Duschene
                 ...
18211                 Holyoke
18212                  Carson
18213                Pasadena
18214                  Austin
18215                El Campo
18216            Garden Grove
18217           Berthoud Pass
18218              Sisterdale
18219            Garden Grove
18220             Shasta Lake
18221                Franklin
18222          Albrightsville
18223              Greenville
18224                 Eufaula
18225             Simi Valley
18226           San Francisco
18227           San Francisco
18228              Kingsville
18229                 Chicago
18230             Pismo Beach
18231             Pismo Beach
18232                    Lodi
18233               Anchorage
18234                Capitola
18235          Fountain Hills
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

In [13]:
type(ufo["City"])

pandas.core.series.Series

In [14]:
ufo.City

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
5                 Valley City
6                 Crater Lake
7                        Alma
8                     Eklutna
9                     Hubbard
10                    Fontana
11                   Waterloo
12                     Belton
13                     Keokuk
14                  Ludington
15                Forest Home
16                Los Angeles
17                  Hapeville
18                     Oneida
19                 Bering Sea
20                   Nebraska
21                        NaN
22                        NaN
23                  Owensboro
24                 Wilderness
25                  San Diego
26                 Wilderness
27                     Clovis
28                 Los Alamos
29               Ft. Duschene
                 ...
18211                 Holyoke
18212                  Carson
18213                Pasadena
18214                  Austin
18215                El Campo
18216            Garden Grove
18217           Berthoud Pass
18218              Sisterdale
18219            Garden Grove
18220             Shasta Lake
18221                Franklin
18222          Albrightsville
18223              Greenville
18224                 Eufaula
18225             Simi Valley
18226           San Francisco
18227           San Francisco
18228              Kingsville
18229                 Chicago
18230             Pismo Beach
18231             Pismo Beach
18232                    Lodi
18233               Anchorage
18234                Capitola
18235          Fountain Hills
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

In [16]:
ufo.Colors Reported  #above it is showing error so,we have to use square brackets because it is taken into two words

SyntaxError: invalid syntax (<ipython-input-16-823f97112488>, line 1)

In [17]:
ufo["Colors Reported"]

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5           NaN
6           NaN
7           NaN
8           NaN
9           NaN
10          NaN
11          NaN
12          RED
13          NaN
14          NaN
15          NaN
16          NaN
17          NaN
18          NaN
19          RED
20          NaN
21          NaN
22          NaN
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
          ...
18211       NaN
18212       NaN
18213     GREEN
18214       NaN
18215       NaN
18216    ORANGE
18217       NaN
18218       NaN
18219       NaN
18220      BLUE
18221       NaN
18222       NaN
18223       NaN
18224       NaN
18225       NaN
18226       NaN
18227       NaN
18228       NaN
18229       NaN
18230       NaN
18231       NaN
18232       NaN
18233       RED
18234       NaN
18235       NaN
18236       NaN
18237       NaN
18238       NaN
18239       RED
18240       NaN
Name: Colors Reported, Length: 18241, dtype: object

In [20]:
"ab"+"cd"

'abcd'

In [25]:
ufo.City+' , '+ufo.State

0                      Ithaca , NY
1                 Willingboro , NJ
2                     Holyoke , CO
3                     Abilene , KS
4        New York Worlds Fair , NY
5                 Valley City , ND
6                 Crater Lake , CA
7                        Alma , MI
8                     Eklutna , AK
9                     Hubbard , OR
10                    Fontana , CA
11                   Waterloo , AL
12                     Belton , SC
13                     Keokuk , IA
14                  Ludington , MI
15                Forest Home , CA
16                Los Angeles , CA
17                  Hapeville , GA
18                     Oneida , TN
19                 Bering Sea , AK
20                   Nebraska , NE
21                             NaN
22                             NaN
23                  Owensboro , KY
24                 Wilderness , WV
25                  San Diego , CA
26                 Wilderness , WV
27                     Clovis , NM
28                 Los Alamos , NM
29               Ft. Duschene , UT
                   ...
18211                 Holyoke , MA
18212                  Carson , CA
18213                Pasadena , CA
18214                  Austin , TX
18215                El Campo , TX
18216            Garden Grove , CA
18217           Berthoud Pass , CO
18218              Sisterdale , TX
18219            Garden Grove , CA
18220             Shasta Lake , CA
18221                Franklin , NH
18222          Albrightsville , PA
18223              Greenville , SC
18224                 Eufaula , OK
18225             Simi Valley , CA
18226           San Francisco , CA
18227           San Francisco , CA
18228              Kingsville , TX
18229                 Chicago , IL
18230             Pismo Beach , CA
18231             Pismo Beach , CA
18232                    Lodi , WI
18233               Anchorage , AK
18234                Capitola , CA
18235          Fountain Hills , AZ
18236              Grant Park , IL
18237             Spirit Lake , IA
18238             Eagle River , WI
18239             Eagle River , WI
18240                    Ybor , FL
Length: 18241, dtype: object

### To create a new series

In [26]:
ufo['location']=ufo.City+' , '+ufo.State
ufo['location']

0                      Ithaca , NY
1                 Willingboro , NJ
2                     Holyoke , CO
3                     Abilene , KS
4        New York Worlds Fair , NY
5                 Valley City , ND
6                 Crater Lake , CA
7                        Alma , MI
8                     Eklutna , AK
9                     Hubbard , OR
10                    Fontana , CA
11                   Waterloo , AL
12                     Belton , SC
13                     Keokuk , IA
14                  Ludington , MI
15                Forest Home , CA
16                Los Angeles , CA
17                  Hapeville , GA
18                     Oneida , TN
19                 Bering Sea , AK
20                   Nebraska , NE
21                             NaN
22                             NaN
23                  Owensboro , KY
24                 Wilderness , WV
25                  San Diego , CA
26                 Wilderness , WV
27                     Clovis , NM
28                 Los Alamos , NM
29               Ft. Duschene , UT
                   ...
18211                 Holyoke , MA
18212                  Carson , CA
18213                Pasadena , CA
18214                  Austin , TX
18215                El Campo , TX
18216            Garden Grove , CA
18217           Berthoud Pass , CO
18218              Sisterdale , TX
18219            Garden Grove , CA
18220             Shasta Lake , CA
18221                Franklin , NH
18222          Albrightsville , PA
18223              Greenville , SC
18224                 Eufaula , OK
18225             Simi Valley , CA
18226           San Francisco , CA
18227           San Francisco , CA
18228              Kingsville , TX
18229                 Chicago , IL
18230             Pismo Beach , CA
18231             Pismo Beach , CA
18232                    Lodi , WI
18233               Anchorage , AK
18234                Capitola , CA
18235          Fountain Hills , AZ
18236              Grant Park , IL
18237             Spirit Lake , IA
18238             Eagle River , WI
18239             Eagle River , WI
18240                    Ybor , FL
Name: location, Length: 18241, dtype: object

### Here we can see that location is added.

In [27]:
ufo.head()

,City,Colors Reported,Shape Reported,State,Time,location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca , NY"
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro , NJ"
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke , CO"
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene , KS"
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair , NY"

In [32]:
ufo.describe()

,City,Colors Reported,Shape Reported,State,Time,location
count,18216,2882,15597,18241,18241,18216
unique,6476,27,27,52,16145,8029
top,Seattle,RED,LIGHT,CA,11/16/1999 19:00,"Seattle , WA"
freq,187,780,2803,2529,27,187

### Why do some pandas commands end with parentheses (and others don't)?

In [5]:
movies=pd.read_csv("http://bit.ly/imdbratings")

In [6]:
movies

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
6,8.9,"The Good, the Bad and the Ugly",NOT RATED,Western,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
9,8.9,Fight Club,R,Drama,139,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
13,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
14,8.8,The Lord of the Rings: The Two Towers,PG-13,Adventure,179,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort..."
15,8.7,Interstellar,PG-13,Adventure,169,"[u'Matthew McConaughey', u'Anne Hathaway', u'J..."
16,8.7,One Flew Over the Cuckoo's Nest,R,Drama,133,"[u'Jack Nicholson', u'Louise Fletcher', u'Mich..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
18,8.7,Goodfellas,R,Biography,146,"[u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']"
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
22,8.7,It's a Wonderful Life,APPROVED,Drama,130,"[u'James Stewart', u'Donna Reed', u'Lionel Bar..."
23,8.7,The Usual Suspects,R,Crime,106,"[u'Kevin Spacey', u'Gabriel Byrne', u'Chazz Pa..."
24,8.7,Se7en,R,Drama,127,"[u'Morgan Freeman', u'Brad Pitt', u'Kevin Spac..."
25,8.6,Life Is Beautiful,PG-13,Comedy,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
26,8.6,Once Upon a Time in the West,PG-13,Western,175,"[u'Henry Fonda', u'Charles Bronson', u'Claudia..."
27,8.6,The Silence of the Lambs,R,Drama,118,"[u'Jodie Foster', u'Anthony Hopkins', u'Lawren..."
28,8.6,Leon: The Professional,R,Crime,110,"[u'Jean Reno', u'Gary Oldman', u'Natalie Portm..."
29,8.6,City Lights,PASSED,Comedy,87,"[u'Charles Chaplin', u'Virginia Cherrill', u'F..."
...,...,...,...,...,...,...
949,7.4,Home Alone,PG,Comedy,103,"[u'Macaulay Culkin', u'Joe Pesci', u'Daniel St..."
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
951,7.4,Sleepy Hollow,R,Drama,105,"[u'Johnny Depp', u'Christina Ricci', u'Miranda..."
952,7.4,Pirate Radio,R,Comedy,117,"[u'Philip Seymour Hoffman', u'Bill Nighy', u'N..."
953,7.4,The NeverEnding Story,PG,Adventure,102,"[u'Noah Hathaway', u'Barret Oliver', u'Tami St..."
954,7.4,X-Men,PG-13,Action,104,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
956,7.4,Manhattan Murder Mystery,PG,Comedy,104,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']"
957,7.4,National Lampoon's Vacation,R,Comedy,98,"[u'Chevy Chase', u""Beverly D'Angelo"", u'Imogen..."
958,7.4,My Sister's Keeper,PG-13,Drama,109,"[u'Cameron Diaz', u'Abigail Breslin', u'Alec B..."
959,7.4,Deconstructing Harry,R,Comedy,96,"[u'Woody Allen', u'Judy Davis', u'Julia Louis-..."
960,7.4,The Way Way Back,PG-13,Comedy,103,"[u'Steve Carell', u'Toni Collette', u'Allison ..."
961,7.4,Capote,R,Biography,114,"[u'Philip Seymour Hoffman', u'Clifton Collins ..."
962,7.4,Driving Miss Daisy,PG,Comedy,99,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay..."
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
965,7.4,Limitless,PG-13,Mystery,105,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor..."
966,7.4,The Simpsons Movie,PG-13,Animation,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
968,7.4,The English Patient,R,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
970,7.4,Wonder Boys,R,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
971,7.4,Death at a Funeral,R,Comedy,90,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew..."
972,7.4,Blue Valentine,NC-17,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [30]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

### described works is as long as there's at least one numeric column it will show you descriptive statistics

In [31]:
movies.describe()

       star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

In [33]:
movies.shape

(979, 6)

In [34]:
movies.dtypes

star_rating       float64
title              object
content_rating     object
genre              object
duration            int64
actors_list        object
dtype: object

In [35]:
type(movies)

pandas.core.frame.DataFrame

In [7]:
movies.describe()

       star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000

In [37]:
movies.describe(include=["object"])

,title,content_rating,genre,actors_list
count,979,976,979,979
unique,975,12,16,969
top,True Grit,R,Drama,"[u'Daniel Radcliffe', u'Emma Watson', u'Rupert..."
freq,2,460,278,6

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 6 columns):
star_rating       979 non-null float64
title             979 non-null object
content_rating    976 non-null object
genre             979 non-null object
duration          979 non-null int64
actors_list       979 non-null object
dtypes: float64(1), int64(1), object(4)
memory usage: 46.0+ KB

In [10]:
movies.columns

Index(['star_rating', 'title', 'content_rating', 'genre', 'duration',
       'actors_list'],
      dtype='object')

In [13]:
movies.values

array([[9.3, 'The Shawshank Redemption', 'R', 'Crime', 142,
        "[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunton']"],
       [9.2, 'The Godfather', 'R', 'Crime', 175,
        "[u'Marlon Brando', u'Al Pacino', u'James Caan']"],
       [9.1, 'The Godfather: Part II', 'R', 'Crime', 200,
        "[u'Al Pacino', u'Robert De Niro', u'Robert Duvall']"],
       ...,
       [7.4, 'Master and Commander: The Far Side of the World', 'PG-13',
        'Action', 138,
        "[u'Russell Crowe', u'Paul Bettany', u'Billy Boyd']"],
       [7.4, 'Poltergeist', 'PG', 'Horror', 114,
        '[u\'JoBeth Williams\', u"Heather O\'Rourke", u\'Craig T. Nelson\']'],
       [7.4, 'Wall Street', 'R', 'Crime', 126,
        "[u'Charlie Sheen', u'Michael Douglas', u'Tamara Tunie']"]],
      dtype=object)

In [15]:
movies.set_index("title",inplace=True)
movies.head()

,star_rating,content_rating,genre,duration,actors_list
title,,,,,
The Shawshank Redemption,9.3,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
The Godfather,9.2,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
The Godfather: Part II,9.1,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
The Dark Knight,9.0,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Pulp Fiction,8.9,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [20]:
movies.sort_index(axis=1,ascending=False)

,star_rating,genre,duration,content_rating,actors_list
title,,,,,
The Shawshank Redemption,9.3,Crime,142,R,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
The Godfather,9.2,Crime,175,R,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
The Godfather: Part II,9.1,Crime,200,R,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
The Dark Knight,9.0,Action,152,PG-13,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Pulp Fiction,8.9,Crime,154,R,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
12 Angry Men,8.9,Drama,96,NOT RATED,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
"The Good, the Bad and the Ugly",8.9,Western,161,NOT RATED,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
The Lord of the Rings: The Return of the King,8.9,Adventure,201,PG-13,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
Schindler's List,8.9,Biography,195,R,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
Fight Club,8.9,Drama,139,R,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh..."
The Lord of the Rings: The Fellowship of the Ring,8.8,Adventure,178,PG-13,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
Inception,8.8,Action,148,PG-13,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
Star Wars: Episode V - The Empire Strikes Back,8.8,Action,124,PG,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
Forrest Gump,8.8,Drama,142,PG-13,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
The Lord of the Rings: The Two Towers,8.8,Adventure,179,PG-13,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort..."
Interstellar,8.7,Adventure,169,PG-13,"[u'Matthew McConaughey', u'Anne Hathaway', u'J..."
One Flew Over the Cuckoo's Nest,8.7,Drama,133,R,"[u'Jack Nicholson', u'Louise Fletcher', u'Mich..."
Seven Samurai,8.7,Drama,207,UNRATED,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
Goodfellas,8.7,Biography,146,R,"[u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']"
Star Wars,8.7,Action,121,PG,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
The Matrix,8.7,Action,136,R,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
City of God,8.7,Crime,130,R,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
It's a Wonderful Life,8.7,Drama,130,APPROVED,"[u'James Stewart', u'Donna Reed', u'Lionel Bar..."
The Usual Suspects,8.7,Crime,106,R,"[u'Kevin Spacey', u'Gabriel Byrne', u'Chazz Pa..."
Se7en,8.7,Drama,127,R,"[u'Morgan Freeman', u'Brad Pitt', u'Kevin Spac..."
Life Is Beautiful,8.6,Comedy,116,PG-13,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
Once Upon a Time in the West,8.6,Western,175,PG-13,"[u'Henry Fonda', u'Charles Bronson', u'Claudia..."
The Silence of the Lambs,8.6,Drama,118,R,"[u'Jodie Foster', u'Anthony Hopkins', u'Lawren..."
Leon: The Professional,8.6,Crime,110,R,"[u'Jean Reno', u'Gary Oldman', u'Natalie Portm..."
City Lights,8.6,Comedy,87,PASSED,"[u'Charles Chaplin', u'Virginia Cherrill', u'F..."
...,...,...,...,...,...
Home Alone,7.4,Comedy,103,PG,"[u'Macaulay Culkin', u'Joe Pesci', u'Daniel St..."
Bound,7.4,Crime,108,R,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
Sleepy Hollow,7.4,Drama,105,R,"[u'Johnny Depp', u'Christina Ricci', u'Miranda..."
Pirate Radio,7.4,Comedy,117,R,"[u'Philip Seymour Hoffman', u'Bill Nighy', u'N..."
The NeverEnding Story,7.4,Adventure,102,PG,"[u'Noah Hathaway', u'Barret Oliver', u'Tami St..."
X-Men,7.4,Action,104,PG-13,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
Zero Dark Thirty,7.4,Drama,157,R,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
Manhattan Murder Mystery,7.4,Comedy,104,PG,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']"
National Lampoon's Vacation,7.4,Comedy,98,R,"[u'Chevy Chase', u""Beverly D'Angelo"", u'Imogen..."
My Sister's Keeper,7.4,Drama,109,PG-13,"[u'Cameron Diaz', u'Abigail Breslin', u'Alec B..."
Deconstructing Harry,7.4,Comedy,96,R,"[u'Woody Allen', u'Judy Davis', u'Julia Louis-..."
The Way Way Back,7.4,Comedy,103,PG-13,"[u'Steve Carell', u'Toni Collette', u'Allison ..."
Capote,7.4,Biography,114,R,"[u'Philip Seymour Hoffman', u'Clifton Collins ..."
Driving Miss Daisy,7.4,Comedy,99,PG,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay..."
La Femme Nikita,7.4,Action,118,R,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
Lincoln,7.4,Biography,150,PG-13,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
Limitless,7.4,Mystery,105,PG-13,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor..."
The Simpsons Movie,7.4,Animation,87,PG-13,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
The Rock,7.4,Action,136,R,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
The English Patient,7.4,Drama,162,R,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."
Law Abiding Citizen,7.4,Crime,109,R,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
Wonder Boys,7.4,Drama,107,R,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
Death at a Funeral,7.4,Comedy,90,R,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew..."
Blue Valentine,7.4,Drama,112,NC-17,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
The Cider House Rules,7.4,Drama,126,PG-13,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
Tootsie,7.4,Comedy,116,PG,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
Back to the Future Part III,7.4,Adventure,118,PG,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
Master and Commander: The Far Side of the World,7.4,Action,138,PG-13,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
Poltergeist,7.4,Horror,114,PG,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
Wall Street,7.4,Crime,126,R,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [21]:
movies.sort_index(axis=1,ascending=False)

,star_rating,genre,duration,content_rating,actors_list
title,,,,,
The Shawshank Redemption,9.3,Crime,142,R,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
The Godfather,9.2,Crime,175,R,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
The Godfather: Part II,9.1,Crime,200,R,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
The Dark Knight,9.0,Action,152,PG-13,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Pulp Fiction,8.9,Crime,154,R,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
12 Angry Men,8.9,Drama,96,NOT RATED,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
"The Good, the Bad and the Ugly",8.9,Western,161,NOT RATED,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."
The Lord of the Rings: The Return of the King,8.9,Adventure,201,PG-13,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
Schindler's List,8.9,Biography,195,R,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
Fight Club,8.9,Drama,139,R,"[u'Brad Pitt', u'Edward Norton', u'Helena Bonh..."
The Lord of the Rings: The Fellowship of the Ring,8.8,Adventure,178,PG-13,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
Inception,8.8,Action,148,PG-13,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
Star Wars: Episode V - The Empire Strikes Back,8.8,Action,124,PG,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
Forrest Gump,8.8,Drama,142,PG-13,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
The Lord of the Rings: The Two Towers,8.8,Adventure,179,PG-13,"[u'Elijah Wood', u'Ian McKellen', u'Viggo Mort..."
Interstellar,8.7,Adventure,169,PG-13,"[u'Matthew McConaughey', u'Anne Hathaway', u'J..."
One Flew Over the Cuckoo's Nest,8.7,Drama,133,R,"[u'Jack Nicholson', u'Louise Fletcher', u'Mich..."
Seven Samurai,8.7,Drama,207,UNRATED,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
Goodfellas,8.7,Biography,146,R,"[u'Robert De Niro', u'Ray Liotta', u'Joe Pesci']"
Star Wars,8.7,Action,121,PG,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
The Matrix,8.7,Action,136,R,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
City of God,8.7,Crime,130,R,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
It's a Wonderful Life,8.7,Drama,130,APPROVED,"[u'James Stewart', u'Donna Reed', u'Lionel Bar..."
The Usual Suspects,8.7,Crime,106,R,"[u'Kevin Spacey', u'Gabriel Byrne', u'Chazz Pa..."
Se7en,8.7,Drama,127,R,"[u'Morgan Freeman', u'Brad Pitt', u'Kevin Spac..."
Life Is Beautiful,8.6,Comedy,116,PG-13,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
Once Upon a Time in the West,8.6,Western,175,PG-13,"[u'Henry Fonda', u'Charles Bronson', u'Claudia..."
The Silence of the Lambs,8.6,Drama,118,R,"[u'Jodie Foster', u'Anthony Hopkins', u'Lawren..."
Leon: The Professional,8.6,Crime,110,R,"[u'Jean Reno', u'Gary Oldman', u'Natalie Portm..."
City Lights,8.6,Comedy,87,PASSED,"[u'Charles Chaplin', u'Virginia Cherrill', u'F..."
...,...,...,...,...,...
Home Alone,7.4,Comedy,103,PG,"[u'Macaulay Culkin', u'Joe Pesci', u'Daniel St..."
Bound,7.4,Crime,108,R,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
Sleepy Hollow,7.4,Drama,105,R,"[u'Johnny Depp', u'Christina Ricci', u'Miranda..."
Pirate Radio,7.4,Comedy,117,R,"[u'Philip Seymour Hoffman', u'Bill Nighy', u'N..."
The NeverEnding Story,7.4,Adventure,102,PG,"[u'Noah Hathaway', u'Barret Oliver', u'Tami St..."
X-Men,7.4,Action,104,PG-13,"[u'Patrick Stewart', u'Hugh Jackman', u'Ian Mc..."
Zero Dark Thirty,7.4,Drama,157,R,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
Manhattan Murder Mystery,7.4,Comedy,104,PG,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']"
National Lampoon's Vacation,7.4,Comedy,98,R,"[u'Chevy Chase', u""Beverly D'Angelo"", u'Imogen..."
My Sister's Keeper,7.4,Drama,109,PG-13,"[u'Cameron Diaz', u'Abigail Breslin', u'Alec B..."
Deconstructing Harry,7.4,Comedy,96,R,"[u'Woody Allen', u'Judy Davis', u'Julia Louis-..."
The Way Way Back,7.4,Comedy,103,PG-13,"[u'Steve Carell', u'Toni Collette', u'Allison ..."
Capote,7.4,Biography,114,R,"[u'Philip Seymour Hoffman', u'Clifton Collins ..."
Driving Miss Daisy,7.4,Comedy,99,PG,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay..."
La Femme Nikita,7.4,Action,118,R,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
Lincoln,7.4,Biography,150,PG-13,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
Limitless,7.4,Mystery,105,PG-13,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor..."
The Simpsons Movie,7.4,Animation,87,PG-13,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
The Rock,7.4,Action,136,R,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
The English Patient,7.4,Drama,162,R,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."
Law Abiding Citizen,7.4,Crime,109,R,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
Wonder Boys,7.4,Drama,107,R,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
Death at a Funeral,7.4,Comedy,90,R,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew..."
Blue Valentine,7.4,Drama,112,NC-17,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
The Cider House Rules,7.4,Drama,126,PG-13,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
Tootsie,7.4,Comedy,116,PG,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
Back to the Future Part III,7.4,Adventure,118,PG,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
Master and Commander: The Far Side of the World,7.4,Action,138,PG-13,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
Poltergeist,7.4,Horror,114,PG,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
Wall Street,7.4,Crime,126,R,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [28]:
movies.sort_values(by="star_rating",ascending=True).head()

,star_rating,content_rating,genre,duration,actors_list
title,,,,,
Wall Street,7.4,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."
Bound,7.4,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
Home Alone,7.4,PG,Comedy,103,"[u'Macaulay Culkin', u'Joe Pesci', u'Daniel St..."
Frances Ha,7.4,R,Comedy,86,"[u'Greta Gerwig', u'Mickey Sumner', u'Adam Dri..."
Eraserhead,7.4,UNRATED,Drama,89,"[u'Jack Nance', u'Charlotte Stewart', u'Allen ..."

In [27]:
movies.sort_index(axis=1).head()

,actors_list,content_rating,duration,genre,star_rating
title,,,,,
The Shawshank Redemption,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...",R,142,Crime,9.3
The Godfather,"[u'Marlon Brando', u'Al Pacino', u'James Caan']",R,175,Crime,9.2
The Godfather: Part II,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv...",R,200,Crime,9.1
The Dark Knight,"[u'Christian Bale', u'Heath Ledger', u'Aaron E...",PG-13,152,Action,9.0
Pulp Fiction,"[u'John Travolta', u'Uma Thurman', u'Samuel L....",R,154,Crime,8.9

In [29]:
movies.sort_values(by=["star_rating","duration"],ascending=True).head()

,star_rating,content_rating,genre,duration,actors_list
title,,,,,
Alice in Wonderland,7.4,G,Animation,75,"[u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha..."
Frances Ha,7.4,R,Comedy,86,"[u'Greta Gerwig', u'Mickey Sumner', u'Adam Dri..."
The Simpsons Movie,7.4,PG-13,Animation,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
Eraserhead,7.4,UNRATED,Drama,89,"[u'Jack Nance', u'Charlotte Stewart', u'Allen ..."
Death at a Funeral,7.4,R,Comedy,90,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew..."

In [30]:
movies.iloc[2,3]# 2nd row and 3rd column,position

200

In [31]:
movies.iloc[5]#5th row

star_rating                                                     8.9
content_rating                                            NOT RATED
genre                                                         Drama
duration                                                         96
actors_list       [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...
Name: 12 Angry Men, dtype: object

In [38]:
movies.loc[3,"content_rating"]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [3] of <class 'int'>

In [40]:
movies.loc[5,:]

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [5] of <class 'int'>

## How do I rename columns in a pandas DataFrame